services:
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=mypassword123
    ports:
      - "6379:6379"
    networks:
      - app-net

  web:
    image: my-app-image
    ports:
      - "3000:3000"
    environment:
      - REDIS_PASSWORD=mySuperSecret123
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-net

networks:
  app-net:
